### ISSUE TITLE
Formatting issues with README

### ISSUE THREAD

**Issue by mismathh** [paulkim26/til-to-html#2]
Suggestions/typos for README.md file:

- For the Command Line Arguments table, some of the arguments are getting cut off and pushed to a new line. Might need to play around with the spacings of the table to correct it.
- Within same table mentioned above, there is a typo within the description of the --output argument
    ommitted --> omitted
- Missing closing brackets in code blocks under Usage heading

Typos in README:

![README Formatting Issues](https://github.com/paulkim26/til-to-html/assets/91957448/5800e098-db70-4875-a4bd-52fba597ded3)

**Comment by paulkim26** [comment]
Thanks for reporting!

Regarding the table truncation, it appears this is a rendering issue with how Github is rendering the table. Looking at other online markdown renderers and in VS code, the issue does not appear elsewhere. The way the table is resized appears to be contingent on the renderer - playing around with i.e. additional dashes or whitespace in the syntax does not change this behaviour in Github unfortunately.

Typo for the word "omitted" corrected for an upcoming PR.

Regarding the usage messages, I believe that this is the correct syntax for what I am trying to express: a mandatory argument that is either a filename or  ("|") a directory.
```
til-to-html [-h | --help] [-v | --version] [-o | --output directory] filename | directory
```

Closing square brackets would indicate that the directory argument is optional, which is incorrect in my understanding. [source](https://en.wikipedia.org/wiki/Usage_message)
```
til-to-html [-h | --help] [-v | --version] [-o | --output directory] [filename | directory]
```

**Comment by mismathh** [comment]
Oh yes, you are correct. I made a mistake. I somehow didn't catch the "directory" portion after --output and assumed that "filename | directory" was part of --output and that the "]" bracket was in the wrong place.
