### ISSUE TITLE
<title>...</title> content does not get updated when there is a title in input files

### ISSUE THREAD

**Issue by mismathh** [paulkim26/til-to-html#5]
Based on the optional requirement stated in the Release 0.1 wiki to parse a title from the input files: if there is a title, it also needs to populate the``<title>...</title>`` with the title from the input file.

Quote from [Release 0.1 Wiki](https://github.com/Seneca-CDOT/topics-in-open-source-2023/wiki/release-0.1)
>1. try to parse a title from your input files. If there is a title, it will be the first line followed by two blank lines. In your generated HTML, use this to populate the \<title>...\</title> and add an \<h1>...\</h1> to the top of the \<body>.

If this was a custom optional requirement, then please disregard this issue.

**Comment by paulkim26** [comment]
Ah I see, I incorrectly interpreted "title" here as the filename but in the quote you provided it refers to the title within the text file, thanks, will change.
