### ISSUE TITLE
Suggestion: Provide more documentation/warnings for Windows users

### ISSUE THREAD

**Issue by mismathh** [paulkim26/til-to-html#6]
As I was trying to run this tool on Windows, setting up WSL was a bit more time-consuming than I expected. 

The WSL Installation link provided was quite adequate, but it appears that if you try to install WSL through the command ``wsl --install`` without checking if the Virtual Machine Platform Windows feature is enabled, WSL won't be able to work. As such, providing a warning/documentation to this might cut down the time for new users to setup. This [website](https://medium.com/@alexads108/install-bun-for-windows-a-modern-javascript-runtime-like-node-or-deno-22b639fad5dc) helped me a lot in setting up my environment.

Additionally, when installing ``Bun``, a tool called ``Unzip`` is required. Command used in WSL terminal to install Unzip:
``sudo apt install unzip``

Providing information that this Unzip utility tool is also required to fully install Bun will be helpful.

**Comment by paulkim26** [comment]
Thanks, these are good things to note, will include with next release.
