### ISSUE TITLE
Add markdown support (Lab#2)

### ISSUE THREAD

**Issue by mismathh** [paulkim26/til-to-html#9]
I'd like to implement two new features to this repo:

- File handling support for `.md` files
- Convert Heading 2 markdown syntax to appropriate HTML tags

I plan to add `.md` support by working within the parseArguments.ts file and wherever it checks if a file ends in `.txt`, I will add in another condition to check if the file also ends in `.md`.

In order to implement Heading 2 markdown conversion, I plan to create another `.ts` within the parse-markdown folder and use regex to convert Heading 2 markdown syntax into `<h2>...</h2>` HTML tag.

**Comment by paulkim26** [comment]
Sounds great, go for it.
